### ISSUE TITLE
Get-LdapConnection.md Documentation Suggestion

### ISSUE THREAD

**Issue by iancrew** [replicaJunction/Ldap#4]
In the file Get-LdapConnection.md, I'd suggest providing a bit more detail about how to generate a credential that'll work with a standard LDAP bind.

I finally found Example 7 at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-credential?view=powershell-6 that got me on the right track to assembling the credentials I needed. Specifically, I now have code that looks like:

```
$LDAPuser="uid=myldapusername,ou=applications,dc=example,dc=com"
$LDAPpass= ConvertTo-SecureString -String "myldappassword" -AsPlainText -Force
$LDAPcredential= New-Object -TypeName SYSTEM.Management.Automation.PSCredential -ArgumentList $LDAPuser, $LDAPpass
$LDAPconnection = Get-LDAPConnection -Server ldap.example.com -Port 636 -Credential $LDAPcredential
```

It works well, just took me a while to figure that out! (And thanks for a useful cmdlet!)

**Comment by replicaJunction** [comment]
Thanks for the kind words!

The only thing that's really unusual about the Credential parameter is that it usually requires a full distinguished name rather than a simple common name, and that's already called out in the documentation. To be on the safe side, though, I've added a line in the documentation to provide a reference back to the documentation on the Get-Credential cmdlet (which includes the example you referenced above).
